version: '3.8'
services:
  worker:
    image: openqa_worker
    build: .
    privileged: true
    devices:
      - /dev/kvm
    volumes:
      - ../webui/workdir/data/factory:/data/factory:rw
      - ../webui/workdir/data/tests:/data/tests:ro
      - ./conf:/data/conf:ro
    environment:
      qemu_no_kvm: 1
    deploy:
      replicas: ${OPENQA_WORKER_REPLICAS}
